---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yoycapit/
    
    # Copy all files and directories (including hidden ones) to the deployment path
    - /bin/cp -ru . $DEPLOYPATH
    
    # Go to the deployment path
    - cd $DEPLOYPATH
    
    # Install Composer dependencies (only production dependencies)
    - composer install --no-dev --optimize-autoloader
    
    # Set correct permissions for Laravel's storage and cache directories
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
    - chown -R yoycapit:yoycapit $DEPLOYPATH/storage
    - chown -R yoycapit:yoycapit $DEPLOYPATH/bootstrap/cache
    
    # Run migrations if necessary
    - php artisan migrate --force
    
    # Cache configuration, routes, and views for performance
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    
    # Optional: Restart queue workers (if you're using queues)
    # - php artisan queue:restart
